AllCops:
  TargetRubyVersion: 1.9

Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

MultilineOperationIndentation:
  EnforcedStyle: indented

MultilineMethodCallIndentation:
  EnforcedStyle: indented
